apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: travelo-postgres
  namespace: travelo
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: travelo
      owner: travelo
      secret:
        name: travelo-secret